/roof_rgbd_camera:
  use_preset: "structure_driver.yaml"
  use_if:
    robot_type: pmb2
    camera_model: structure
    add_on_module: cobra
  ros__parameters:
    device_id: "${serial_number_camera_0}"
    ir_frame_id: "roof_rgbd_camera_optical_frame"
    rgb_frame_id: "roof_rgbd_camera_optical_frame"
    depth_frame_id: "roof_rgbd_camera_depth_optical_frame"
  remappings:
    depth/image: "depth_registered/image_raw"

/roof_rgbd_camera_proc:
  use_preset: "depth_image_processing.yaml"
  use_if:
    robot_type: pmb2
    camera_model: structure
    add_on_module: cobra
  remappings:
    image_rect: "depth/image_raw"
    camera_info: "depth/camera_info"
    points: "depth/points"
    points/draco: "depth/points/draco"
    points/zlib: "depth/points/zlib"
    points/zstd: "depth/points/zstd"

/base_rgbd_camera:
  use_preset: "structure_driver.yaml"
  use_if:
    robot_type: pmb2
    camera_model: structure
    add_on_module: cobra
  ros__parameters:
    device_id: "${serial_number_camera_1}"
    ir_frame_id: "base_rgbd_camera_optical_frame"
    rgb_frame_id: "base_rgbd_camera_optical_frame"
    depth_frame_id: "base_rgbd_camera_depth_optical_frame"
  remappings:
    depth/image: "depth_registered/image_raw"

/base_rgbd_camera_proc:
  use_preset: "depth_image_processing.yaml"
  use_if:
    robot_type: pmb2
    camera_model: structure
    add_on_module: cobra
  remappings:
    image_rect: "depth/image_raw"
    camera_info: "depth/camera_info"
    points: "depth/points"
    points/draco: "depth/points/draco"
    points/zlib: "depth/points/zlib"
    points/zstd: "depth/points/zstd"